### ISSUE TITLE
stopping and starting the app service

### ISSUE THREAD

**Issue by SuperDuperOne** [vanderby/SonarQube-AzureAppService#17] opened 2019-10-31 14:03 UTC
Firstly, 
I would like to say that this is great when working however, 
whenever I attempt to update the marketplace plugins within SonarQube, (azure AD, SonarQube Gateway and rule update, etc)

the app restart but hits 502/404/400 error....even after restarting the box several times.

I'm using the S2 and P1 
because it seems to be complaining about memory and high CPU.

![image](https://user-images.githubusercontent.com/23457220/67953401-fa2fd780-fbe6-11e9-82f0-624813254278.png)

I;ve been tempted to not do any updates to SonarQube because we need static code analyzing in place asap.

any ideas?

**Comment by vanderby** [comment] 2019-11-01 14:19
I don't know off the top of my head without digging in. Do the log files give any additional details? Do you have any additional app settings? 

Does this happen when any plugin is installed or just updated? Is there a particular plugin that gets installed/updated that is the root cause of these?

It may be a few days before I have some free time to try and repro.

**Comment by vanderby** [comment] 2019-11-04 02:25
I tried installing just AAD plugin from a fresh install (SQ v8) and this is the error in the sonar.log file.

ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : D:\home\site\wwwroot\sonarqube-8.0\extensions\plugins\sonar-auth-aad-plugin-1.1.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.core.platform.PluginInfo.create(PluginInfo.java:412)
	at org.sonar.server.plugins.ServerPluginRepository.overrideAndRegisterPlugin(ServerPluginRepository.java:189)
	at org.sonar.server.plugins.ServerPluginRepository.moveDownloadedPlugins(ServerPluginRepository.java:146)
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:104)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:109)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel2Container(PlatformImpl.java:179)
	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: D:\home\site\wwwroot\sonarqube-8.0\extensions\plugins\sonar-auth-aad-plugin-1.1.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 28 common frames omitted

**Comment by vanderby** [comment] 2019-11-05 02:03
Does the app eventually work after the restarts? After I installed the AAD plugin it restarted (which took a few minutes), but came up normally. I haven't tried configuring the AAD plugin yet.

**Comment by vanderby** [comment] 2019-11-06 07:16
On another note, when updating the plugins (I tried the C# one), SQ did fail to start. I saw this error message in sonar.log
2019.11.06 00:04:23 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Found two versions of the plugin SonarC# [csharp] in the directory extensions/plugins. Please remove one of sonar-csharp-plugin-8.0.0.9566.jar or sonar-csharp-plugin-7.17.0.9346.jar.

Removing the extra jar fixed that issue.

**Comment by SuperDuperOne** [comment] 2019-11-06 09:47
Hi @vanderby 
thanks for looking into this, 
I've now hit this wall when when I reset the profile and restarted the service.

"The specified CGI application encountered an error and the server terminated the process."

where I are you finding these logs?
are you using the MS portal console?

**Comment by SuperDuperOne** [comment] 2019-11-06 10:10
even without install any additional plugins and I just simply restart the machine from the azure portal, I get: 
The specified CGI application encountered an error and the server terminated the process.

**Comment by SuperDuperOne** [comment] 2019-11-06 10:48
reading this and this: 
https://stackoverflow.com/questions/33645242/the-specified-cgi-application-encountered-an-error-and-the-server-terminated-the

https://code-examples.net/en/q/20162ba

I can only see /d/local/Config/rootweb.config

**Comment by vanderby** [comment] 2019-11-06 13:10
@SuperDuperOne 
To view the logs, you can use the Kudu site or the App Service editor blade (https://xxxx.scm.azurewebsites.net/dev/wwwroot/) thenwwwroot\sonarqube-X.X\logs

The main ones I find useful are sonar.log and web.log.

**Comment by SuperDuperOne** [comment] 2019-11-06 14:04
cant get to it since it's giving me this:
"The specified CGI application encountered an error and the server terminated the process."
i'll have to check out the Kudu way..

it would be good I could remote onto the box....
have you ever seen the above error before?

no matter how many times I restart the box I cant get it to work.
is it worth rebuilding again, I've done nothing but, install a plugin and getting all these errors


![image](https://user-images.githubusercontent.com/23457220/68304757-563ea400-009e-11ea-8662-aa1fc7f514a3.png)

**Comment by vanderby** [comment] 2019-11-06 16:02
I have not seen that error before. The App Service editor blade is in the Azure Portal for the App Service, not the SQ website. 

You can absolutely try deploying a new web app to see what particular action started to cause these issues. That would greatly help in finding the root cause.

**Comment by SuperDuperOne** [comment] 2019-11-07 11:41
Ok.
I will be deploying again to Azure, 
and once up and running, i will restart the box and try connect to it. 
will update here again shortly.

**Comment by vanderby** [comment] 2019-11-07 15:36
You shouldn't need to restart after deploying. It may take up to 10 minutes to start depending on the SKU you select.

AAD plugin is not the issue. I was able to configure it as normal.

There is an issue with updating plugins #22 that has a manual workaround.

**Comment by SuperDuperOne** [comment] 2019-11-07 20:53
I see, 
however when I have installed a plugin, SonarQube suggest that I restart the server (within the UI) in order for the plugin to be installed, when I have clicked restart Server I would get that error message:
_The specified CGI application encountered an error and the server terminated the process._

I have had the SQ up and running so far, but will need to get AAD plugin installed and configure for company use, which again, SQ will suggest that I restart in order for install to complete.

I will upload log shortly.

**Comment by SuperDuperOne** [comment] 2019-11-08 09:02
update: 
so far so good... nothing odd in the logs either. 
I will try getting AAD working fully and attach a databases.

**Comment by vanderby** [comment] 2019-11-09 14:33
I just updated the HttpPlatformHandlerStartup.ps1 script to check for and remove duplicate plugins on startup. That will help alleviate part of your problem.

**Comment by SuperDuperOne** [comment] 2019-11-11 15:20
thanks for your help on this @vanderby 
the box has been running good so far.
i;m trying to attach an Azure SQL database to the box but every time i make changes to the sonar.properties file it change it back to the default H2 database...

i have removed the connection to you github also so there is no continuous deployment configured.

any idea?

**Comment by vanderby** [comment] 2019-11-11 20:44
@SuperDuperOne 
Set the properties through the App Service config editor. The startup script will update the sonar.properties file for you as per #15 

Specifically in your case set sonar.jdbc.username and sonar.jdbc.password.

This makes slot swapping more useful as well as easier to update the settings.

**Comment by SuperDuperOne** [comment] 2019-11-11 21:02
Thanks @vanderby, 
however I have already done so, and to test if the Azure Database gets picked up, I save the changes in App Service Config Editor, restart the SonarQube to accept the changes, 
when the box starts up again, my added database config gets commented out...

below is the current database settings:

<img width="787" alt="Screen Shot 2019-11-11 at 20 54 51" src="https://user-images.githubusercontent.com/23457220/68620547-98fce380-04c5-11ea-8ceb-1bcbde344130.png">

below is my current changes to the sonar.properties file (see screenshot timestamp)
<img width="1358" alt="Screen Shot 2019-11-11 at 20 51 58" src="https://user-images.githubusercontent.com/23457220/68620328-268c0380-04c5-11ea-8af9-0b3f262eedb3.png"> Screen Shot 2019-11-11 at 20 51 58

below after the box starts up again (see screenshot timestamp)

<img width="1290" alt="Screen Shot 2019-11-11 at 21 01 15" src="https://user-images.githubusercontent.com/23457220/68620943-7f0fd080-04c6-11ea-8080-00323cf74af2.png"> Screen Shot 2019-11-11 at 21 01 15

**Comment by vanderby** [comment] 2019-11-11 23:18
@SuperDuperOne 
What does your app settings look like? Yours should look similar to:
![image](https://user-images.githubusercontent.com/28767221/68628731-24b34780-04a7-11ea-9dce-9ef1ffa7711f.png)

The brief instructions on this are here: https://github.com/vanderby/SonarQube-AzureAppService#passthrough-application-settings

**Comment by SuperDuperOne** [comment] 2019-11-12 09:56
Following your README and comment above I added the;
url, password and username.

I followed your recomendation from [here ](https://github.com/vanderby/SonarQube-AzureAppService#passthrough-application-settings) however in Azure Portal > SQL databases > connection Strings I added the JDBC which give me a longer url

![image](https://user-images.githubusercontent.com/23457220/68660872-e31bae80-0531-11ea-8cd7-cbd0ee3ce9b4.png)

and currently, this is in happening within the logs.
![image](https://user-images.githubusercontent.com/23457220/68660957-07778b00-0532-11ea-94db-082bd94ead80.png)

![image](https://user-images.githubusercontent.com/23457220/68661060-3ee63780-0532-11ea-86d5-1ea36f6969c4.png)

i'm hoping this is only temporary :(

**Comment by SuperDuperOne** [comment] 2019-11-12 11:08
@vanderby 
After a few endless days and nights, 
I've finally got it working! with the azure sql db in place, the ability to restart SQ and it not to hang, i'm also able to install apps too! 
Thank you kindly for the help, it was been much appreciated and informative.


I did however, run into this error: 
2019.11.12 10:21:27 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: Database collation must be case-sensitive and accent-sensitive. It is SQL_Latin1_General_CP1_CI_AS but should be SQL_Latin1_General_CP1_CS_AS.

I simply created a new db and change the collation.

**Comment by vanderby** [comment] 2019-11-12 12:55
I'm glad to hear you got it working. Thanks for finding a few bugs for me. The case sensitive/scent sensitive issue is noted in the readme too since it usually burns people.

I'm closing this issue. Feel free to open a new issue if you run into more problems.

**Closed by vanderby** 2019-11-12 12:55 UTC
